name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool --version 5.*
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Execute GitVersion
      id: version
      run: dotnet-gitversion /output buildserver

    - name: Replace version in vsixmanifest
      run: (Get-Content NoBracesOnSingleLineReturnStatement\NoBracesOnSingleLineReturnStatement.Vsix\source.extension.vsixmanifest) -replace 'Version="1.0.0"', 'Version="${{ env.GitVersion_MajorMinorPatch }}"' | Set-Content NoBracesOnSingleLineReturnStatement\NoBracesOnSingleLineReturnStatement.Vsix\source.extension.vsixmanifest

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
